export const SET_IDENTIFIER = 'company/SET_IDENTIFIER'
export const SET_COMPANY = 'company/SET_COMPANY'
export const SET_COMPANY_ATTRIBUTE = 'company/SET_COMPANY_ATTRIBUTE'
export const SET_CANTON_LIST = 'company/SET_CANTON_LIST'
export const SET_DISTRITO_LIST = 'company/SET_DISTRITO_LIST'
export const SET_BARRIO_LIST = 'company/SET_BARRIO_LIST'
export const SET_BRANCH_LIST = 'company/SET_BRANCH_LIST'
export const SET_REPORT_RESULTS = 'company/SET_REPORT_RESULTS'
export const SET_COMPANY_PAGE_ERROR = 'company/SET_COMPANY_PAGE_ERROR'
export const SET_LOGO_PAGE_ERROR = 'company/SET_LOGO_PAGE_ERROR'
export const SET_REPORTS_PAGE_ERROR = 'company/SET_REPORTS_PAGE_ERROR'

