export const SET_ACTIVE_SECTION = 'invoice/SET_ACTIVE_SECTION'
export const SET_INVOICE_SESSION = 'invoice/SET_INVOICE_SESSION'
export const SET_COMPANY = 'invoice/SET_COMPANY'
export const SET_COMPANY_ATTRIBUTE = 'invoice/SET_COMPANY_ATTRIBUTE'
export const SET_CANTON_LIST = 'invoice/SET_CANTON_LIST'
export const SET_DISTRITO_LIST = 'invoice/SET_DISTRITO_LIST'
export const SET_BARRIO_LIST = 'invoice/SET_BARRIO_LIST'
export const SET_BRANCH_LIST = 'invoice/SET_BRANCH_LIST'
export const SET_REPORT_RESULTS = 'invoice/SET_REPORT_RESULTS'

