export const SET_DESCRIPTION = 'invoice/SET_DESCRIPTION'
export const SET_QUANTITY = 'invoice/SET_QUANTITY'
export const SET_PRICE = 'invoice/SET_PRICE'
export const SET_PRODUCTS_DETAIL = 'invoice/SET_PRODUCTS_DETAIL'
export const SET_SUMMARY = 'invoice/SET_SUMMARY'
export const SET_PAYMENT_ID = 'invoice/SET_PAYMENT_ID'
export const SET_BRANCH_ID = 'invoice/SET_BRANCH_ID'
export const SET_SUCCESSFUL = 'invoice/SET_SUCCESSFUL'
export const SET_LIST_PAGE = 'invoice/SET_LIST_PAGE'
export const SET_LIST_COUNT = 'invoice/SET_LIST_COUNT'
export const SET_LIST = 'invoice/SET_LIST'

