export const LOGIN = 'session/LOGIN'
export const LOGOUT = 'session/LOGOUT'
export const SET_LOGIN_ERROR = 'session/SET_LOGIN_ERROR'
export const SET_ACTIVE_HOME_SECTION = 'session/SET_ACTIVE_HOME_SECTION'
export const SET_BRANCH_LIST = 'session/SET_BRANCH_LIST'
export const SET_TERMINAL_LIST = 'session/SET_TERMINAL_LIST'
export const SET_BRANCH = 'session/SET_BRANCH'
export const SET_TERMINAL = 'session/SET_TERMINAL'
export const SET_COMPANY = 'session/SET_COMPANY'
export const SET_COMPANY_ATTRIBUTE = 'session/SET_COMPANY_ATTRIBUTE'
export const SET_CANTON_LIST = 'session/SET_CANTON_LIST'
export const SET_DISTRITO_LIST = 'session/SET_DISTRITO_LIST'
export const SET_BARRIO_LIST = 'session/SET_BARRIO_LIST'
export const SET_COMPANY_PAGE_ERROR = 'session/SET_COMPANY_PAGE_ERROR'
export const SET_LOGO_PAGE_ERROR = 'session/SET_LOGO_PAGE_ERROR'

