export const LOGIN = 'session/LOGIN'
export const LOGOUT = 'session/LOGOUT'
export const SET_COMPANY = 'session/SET_COMPANY'
export const SET_BRANCH_ID = 'session/SET_BRANCH_ID'
export const SET_PRINTER = 'session/SET_PRINTER'
