export const SET_LIST_PAGE = 'customer/SET_LIST_PAGE'
export const SET_LIST_COUNT = 'customer/SET_LIST_COUNT'
export const SET_LIST = 'customer/SET_LIST'
export const SET_CUSTOMER = 'customer/SET_CUSTOMER'
export const SET_PRICE_TYPE_LIST = 'customer/SET_PRICE_TYPE_LIST'
export const SET_CUSTOMER_ATTRIBUTE = 'customer/SET_CUSTOMER_ATTRIBUTE'
