import {
  ProductType,
  InvoiceType,
  WorkingOrderType,
  ReceiptType,
  PaymentDetailsType,
  CustomerType,
  CompanyType,
  ProductDetailsType,
  CustomerDetailsType,
} from "types/domain";

export const defaultCompany: CompanyType = {
  id: 0,
  mode: 1,
  identifier: "",
  name: "",
  comercialName: "",
  provinceId: 1,
  cantonId: 1,
  districtId: 1,
  neighborhoodId: 1,
  address: "",
  phoneNumber: "",
  notificationEmail: "",
  currencyType: 1,
  activityCode: "",
  simplifyRegimen: false,
  economicActivityList: [],
  ivaTaxIncluded: false,
  idTypeList: [],
  taxTypeList: [],
  exonerationTypeList: [],
  priceTypeList: [],
  productTypeList: [],
};

export const defaultCustomerDetails: CustomerDetailsType = {
  id: 1,
  name: "CLIENTE DE CONTADO",
  phoneNumber: "",
  priceTypeId: 1,
  exonerationType: 1,
  differentiatedTaxRateApply: false,
  taxRate: 13,
  exonerationRef: "",
  exoneratedBy: "",
  exonerationDate: "01/01/2000",
  exonerationPercentage: 0,
};

export const defaultCustomer: CustomerType = {
  typeId: 1,
  identifier: "",
  name: "",
  companyName: "",
  address: "",
  phoneNumber: "",
  faxNumber: "",
  email: "",
  vendorId: 1,
  priceTypeId: 1,
  differentiatedTaxRateApply: false,
  taxTypeId: 8,
  exonerationType: 1,
  exonerationRef: "",
  exoneratedBy: "",
  exonerationDate: "",
  exonerationPercentage: 0,
  creditAllowed: false,
};

export const defaultPaymentDetails: PaymentDetailsType = {
  paymentId: 1,
  description: "EFECTIVO",
  amount: 0,
};

export const defaultInvoiceProduct: ProductDetailsType = {
  id: 0,
  code: "",
  description: "",
  quantity: 1,
  taxRate: 13,
  unit: "UND",
  price: 0,
  costPrice: 0,
  instalationPrice: 0,
};

export const defaultReceiptProduct: ProductDetailsType = {
  code: "",
  description: "",
  quantity: 1,
  taxRate: 13,
  unit: "UND",
  price: 0,
};

export const defaultProduct: ProductType = {
  id: null,
  companyId: 0,
  type: 1,
  category: 0,
  code: "",
  providerCode: "",
  cabysCode: "",
  image: "",
  taxTypeId: 8,
  taxRate: 13,
  providerId: 0,
  description: "",
  costPrice: 0,
  untaxPrice1: 0,
  taxPrice1: 0,
  untaxPrice2: 0,
  taxPrice2: 0,
  untaxPrice3: 0,
  taxPrice3: 0,
  untaxPrice4: 0,
  taxPrice4: 0,
  untaxPrice5: 0,
  taxPrice5: 0,
  observation: "",
  brand: "",
  active: true,
  discountPercentage: 0,
  priceChangeAllowed: false,
  minInventory: 0,
};

export const defaultInvoice: InvoiceType = {
  invoiceId: 0,
  consecutive: 0,
  reference: "",
  date: "",
  activityCode: 0,
  customerDetails: defaultCustomerDetails,
  productDetails: defaultInvoiceProduct,
  productDetailList: [],
  paymentDetailsList: [defaultPaymentDetails],
  vendorId: 0,
  summary: {
    taxed: 0,
    exonerated: 0,
    exempt: 0,
    subTotal: 0,
    taxes: 0,
    total: 0,
    totalCost: 0,
    cashAmount: 0,
  },
  comment: "",
  successful: false,
};

export const defaultWorkingOrder: WorkingOrderType = {
  id: 0,
  consecutive: 0,
  date: "",
  cashAdvance: 0,
  invoiceId: 0,
  status: "on-progress",
  activityCode: 0,
  customerDetails: defaultCustomerDetails,
  productDetails: defaultInvoiceProduct,
  productDetailList: [],
  paymentDetailsList: [],
  vendorId: 0,
  summary: {
    taxed: 0,
    exonerated: 0,
    exempt: 0,
    subTotal: 0,
    taxes: 0,
    total: 0,
    totalCost: 0,
    cashAmount: 0,
  },
  delivery: {
    phone: "",
    address: "",
    description: "",
    date: "",
    time: "",
    details: "",
  },
};

export const defaultReceipt: ReceiptType = {
  receiptId: 0,
  activityCode: 0,
  issuer: {
    typeId: 0,
    id: "",
    name: "",
    comercialName: "",
    address: "",
    phone: "",
    email: "",
  },
  productDetails: defaultReceiptProduct,
  productDetailList: [],
  summary: {
    taxed: 0,
    exonerated: 0,
    exempt: 0,
    subTotal: 0,
    taxes: 0,
    total: 0,
    totalCost: 0,
    cashAmount: 0,
  },
  exoneration: {
    type: 1,
    ref: "",
    exoneratedBy: "",
    date: "01/01/2000",
    percentage: 0,
  },
  successful: false,
};
