import {
  BranchType,
  CategoryType,
  CompanyType,
  CreditNoteType,
  CustomerDetailsType,
  CustomerEntityType,
  InvoiceType,
  PaymentInfoType,
  PaymentMethodType,
  ProductDetailsType,
  ProductType,
  ProformaType,
  ReceiptType,
  ServicePointType,
  SummaryType,
  WorkingOrderType,
} from "types/domain";

import { ORDER_STATUS } from "./constants";

export const defaultCompany: CompanyType = {
  IdEmpresa: 0,
  IdTipoIdentificacion: 0,
  Identificacion: "",
  NombreEmpresa: "",
  NombreComercial: "",
  IdProvincia: 1,
  IdCanton: 1,
  IdDistrito: 1,
  Direccion: "",
  Telefono1: "",
  Telefono2: "",
  CorreoNotificacion: "",
  Modalidad: 1,
  Logotipo: "",
  TipoContrato: 1,
  IdTipoMoneda: 1,
  FechaVence: "",
  RegimenSimplificado: false,
  ActividadEconomicaEmpresa: [],
  CantidadDisponible: 0,
  LineasPorFactura: 16,
  Contabiliza: false,
  AutoCompletaProducto: false,
  PermiteFacturar: true,
  RecepcionGastos: true,
  IngresaPagoCliente: false,
  PrecioVentaIncluyeIVA: false,
  ImprimeTiqueteAlFacturar: false,
  HabilitaFacturacionMonedaExtranjera: false,
  HabilitaPreFactura: false,
  MontoRedondeoDescuento: 0,
  LeyendaFactura: "",
  LeyendaProforma: "",
  LeyendaApartado: "",
  LeyendaOrdenServicio: "",
  Usuario: { Token: "" },
};

export const defaultBranch: BranchType = {
  IdEmpresa: 0,
  IdSucursal: 0,
  NombreSucursal: "",
  Direccion: "",
  Telefono: "",
  CorreoElectronico: "",
  MontoCierreEfectivo: 0,
};

export const defaultCredentials = {
  UsuarioHacienda: "",
  ClaveHacienda: "",
  NombreCertificado: "",
  PinCertificado: "",
};

export const defaultSummary: SummaryType = {
  taxed: 0,
  exonerated: 0,
  exempt: 0,
  subTotal: 0,
  taxes: 0,
  total: 0,
  totalCost: 0,
  cashAmount: 0,
};

export const defaultCustomerDetails: CustomerDetailsType = {
  id: 1,
  name: "CLIENTE DE CONTADO",
  comercialName: "",
  email: "",
  phoneNumber: "",
  activityCode: "",
  exonerationType: 1,
  exonerationRef: "",
  exonerationRef2: "",
  exonerationRef3: "",
  exoneratedById: 1,
  exonerationDate: "2000-01-01T23:59:59",
  exonerationPercentage: 0,
  priceTypeId: 1,
};

export const defaultCustomer: CustomerEntityType = {
  IdEmpresa: 0,
  IdCliente: 0,
  IdTipoIdentificacion: 0,
  Identificacion: "",
  Nombre: "CLIENTE DE CONTADO",
  NombreComercial: "",
  Direccion: "",
  Telefono: "",
  Celular: "",
  Fax: "",
  CorreoElectronico: "",
  IdTipoPrecio: 1,
  IdTipoExoneracion: 1,
  IdNombreInstExoneracion: 1,
  NumDocExoneracion: "",
  ArticuloExoneracion: "",
  IncisoExoneracion: "",
  FechaEmisionDoc: "2000-01-01T23:59:59",
  PorcentajeExoneracion: 0,
  PermiteCredito: false,
  CodigoActividad: "",
};

export const defaultPaymentMethod: PaymentMethodType = {
  paymentId: 1,
  bankId: 0,
  description: "EFECTIVO",
  amount: 0,
};

export const defaultProductDetails: ProductDetailsType = {
  id: 0,
  code: "",
  description: "",
  additionalInformation: "",
  quantity: "1",
  taxRate: 13,
  unit: "UND",
  price: "0",
  costPrice: 0,
  disccountRate: 0,
  isService: false,
};

export const defaultProduct: ProductType = {
  IdProducto: 0,
  IdEmpresa: 0,
  Tipo: 1,
  IdLinea: 0,
  Codigo: "",
  CodigoProveedor: "",
  CodigoClasificacion: "",
  Imagen: "",
  IdImpuesto: 8,
  Descripcion: "",
  PrecioCosto: 0,
  PrecioVenta1: 0,
  PrecioVenta2: 0,
  PrecioVenta3: 0,
  PrecioVenta4: 0,
  PrecioVenta5: 0,
  Observacion: "",
  Marca: "",
  Activo: true,
  PorcDescuento: 0,
  ModificaPrecio: false,
  IndExistencia: 0,
};

export const defaultCategory: CategoryType = {
  IdLinea: 0,
  IdEmpresa: 0,
  Descripcion: "",
  Tipo: 1,
  ImpresoraTiquete: "",
  LineaPorSucursal: [],
};

export const defaultInvoice: InvoiceType = {
  invoiceId: 0,
  consecutive: 0,
  date: "",
  activityCode: 0,
  customerDetails: defaultCustomerDetails,
  productDetails: defaultProductDetails,
  productDetailsList: [],
  paymentMethodList: [defaultPaymentMethod],
  summary: defaultSummary,
  comment: "",
  cashAdvance: 0,
  currency: 1,
  paid: false,
};

export const defaultCreditNote: CreditNoteType = {
  creditNoteId: 0,
  date: "",
  totalAmount: 0,
  balance: 0,
  details: "",
};

export const defaultWorkingOrder: WorkingOrderType = {
  id: 0,
  servicePointId: 0,
  consecutive: 0,
  date: "",
  cashAdvance: 0,
  invoiceId: 0,
  status: ORDER_STATUS.READY,
  productDetails: defaultProductDetails,
  productDetailsList: [],
  delivery: {
    phone: "",
    address: "",
    description: "",
    date: "",
    time: "",
    details: "",
  },
};

export const defaultReceipt: ReceiptType = {
  receiptId: 0,
  activityCode: 0,
  issuer: {
    typeId: 0,
    id: "",
    name: "",
    comercialName: "",
    activityCode: "",
    reference: "",
    address: "",
    phone: "",
    email: "",
  },
  productDetails: defaultProductDetails,
  productDetailsList: [],
  summary: {
    taxed: 0,
    exonerated: 0,
    exempt: 0,
    subTotal: 0,
    taxes: 0,
    total: 0,
    totalCost: 0,
    cashAmount: 0,
  },
  exoneration: {
    type: 1,
    ref: "",
    ref2: "",
    ref3: "",
    exoneratedById: 1,
    date: "2000-01-01T23:59:59",
    percentage: 0,
  },
  currency: 1,
  successful: false,
};

export const defaultProforma: ProformaType = {
  proformaId: 0,
  consecutive: 0,
  date: "",
  customerDetails: defaultCustomerDetails,
  productDetails: defaultProductDetails,
  productDetailsList: [],
  currency: 1,
  summary: {
    taxed: 0,
    exonerated: 0,
    exempt: 0,
    subTotal: 0,
    taxes: 0,
    total: 0,
    totalCost: 0,
    cashAmount: 0,
  },
  comment: "",
  successful: false,
};

export const defaultServicePoint: ServicePointType = {
  IdPunto: 0,
  IdEmpresa: 0,
  IdSucursal: 0,
  Descripcion: "",
  Activo: true,
};

export const defaultPaymentInfo: PaymentInfoType = {
  totalSaved: 0,
  totalPaid: 0,
  activityCode: 0,
  customerDetails: defaultCustomerDetails,
  paymentMethodList: [defaultPaymentMethod],
  summary: defaultSummary,
};
