export const START_LOADER = 'ui/START_LOADER'
export const STOP_LOADER = 'ui/STOP_LOADER'
export const SET_ACTIVE_INFO_SECTION = 'ui/SET_ACTIVE_INFO_SECTION'
export const SET_ERROR_MESSAGE = 'ui/SET_ERROR_MESSAGE'
