export const START_LOADER = 'billing/ui/START_LOADER'
export const STOP_LOADER = 'billing/ui/STOP_LOADER'
export const SET_ACTIVE_SECTION = 'billing/ui/SET_ACTIVE_SECTION'
export const SET_ERROR_MESSAGE = 'billing/ui/SET_ERROR_MESSAGE'
export const SET_CANTON_LIST = 'session/SET_CANTON_LIST'
export const SET_DISTRITO_LIST = 'session/SET_DISTRITO_LIST'
export const SET_BARRIO_LIST = 'session/SET_BARRIO_LIST'
export const SET_BRANCH_LIST = 'session/SET_BRANCH_LIST'
